<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesSeeder extends Seeder
{
    public function run()
    {
        $countries = [
            ['name' => ['en' => 'Afghanistan', 'ar' => 'أفغانستان']],
            ['name' => ['en' => 'Albania', 'ar' => 'ألبانيا']],
            ['name' => ['en' => 'Algeria', 'ar' => 'الجزائر']],
            ['name' => ['en' => 'Andorra', 'ar' => 'أندورا']],
            ['name' => ['en' => 'Angola', 'ar' => 'أنغولا']],
            ['name' => ['en' => 'Antigua and Barbuda', 'ar' => 'أنتيغوا وباربودا']],
            ['name' => ['en' => 'Argentina', 'ar' => 'الأرجنتين']],
            ['name' => ['en' => 'Armenia', 'ar' => 'أرمينيا']],
            ['name' => ['en' => 'Australia', 'ar' => 'أستراليا']],
            ['name' => ['en' => 'Austria', 'ar' => 'النمسا']],
            ['name' => ['en' => 'Azerbaijan', 'ar' => 'أذربيجان']],
            ['name' => ['en' => 'Bahamas', 'ar' => 'البهاما']],
            ['name' => ['en' => 'Bahrain', 'ar' => 'البحرين']],
            ['name' => ['en' => 'Bangladesh', 'ar' => 'بنغلاديش']],
            ['name' => ['en' => 'Barbados', 'ar' => 'باربادوس']],
            ['name' => ['en' => 'Belarus', 'ar' => 'بيلاروسيا']],
            ['name' => ['en' => 'Belgium', 'ar' => 'بلجيكا']],
            ['name' => ['en' => 'Belize', 'ar' => 'بليز']],
            ['name' => ['en' => 'Benin', 'ar' => 'بنين']],
            ['name' => ['en' => 'Bhutan', 'ar' => 'بوتان']],
            ['name' => ['en' => 'Bolivia', 'ar' => 'بوليفيا']],
            ['name' => ['en' => 'Bosnia and Herzegovina', 'ar' => 'البوسنة والهرسك']],
            ['name' => ['en' => 'Botswana', 'ar' => 'بوتسوانا']],
            ['name' => ['en' => 'Brazil', 'ar' => 'البرازيل']],
            ['name' => ['en' => 'Brunei', 'ar' => 'بروناي']],
            ['name' => ['en' => 'Bulgaria', 'ar' => 'بلغاريا']],
            ['name' => ['en' => 'Burkina Faso', 'ar' => 'بوركينا فاسو']],
            ['name' => ['en' => 'Burundi', 'ar' => 'بوروندي']],
            ['name' => ['en' => 'Cabo Verde', 'ar' => 'الرأس الأخضر']],
            ['name' => ['en' => 'Cambodia', 'ar' => 'كمبوديا']],
            ['name' => ['en' => 'Cameroon', 'ar' => 'الكاميرون']],
            ['name' => ['en' => 'Canada', 'ar' => 'كندا']],
            ['name' => ['en' => 'Central African Republic', 'ar' => 'جمهورية أفريقيا الوسطى']],
            ['name' => ['en' => 'Chad', 'ar' => 'تشاد']],
            ['name' => ['en' => 'Chile', 'ar' => 'تشيلي']],
            ['name' => ['en' => 'China', 'ar' => 'الصين']],
            ['name' => ['en' => 'Colombia', 'ar' => 'كولومبيا']],
            ['name' => ['en' => 'Comoros', 'ar' => 'جزر القمر']],
            ['name' => ['en' => 'Congo (Democratic Republic)', 'ar' => 'جمهورية الكونغو الديمقراطية']],
            ['name' => ['en' => 'Congo (Republic)', 'ar' => 'جمهورية الكونغو']],
            ['name' => ['en' => 'Costa Rica', 'ar' => 'كوستاريكا']],
            ['name' => ['en' => 'Croatia', 'ar' => 'كرواتيا']],
            ['name' => ['en' => 'Cuba', 'ar' => 'كوبا']],
            ['name' => ['en' => 'Cyprus', 'ar' => 'قبرص']],
            ['name' => ['en' => 'Czechia', 'ar' => 'التشيك']],
            ['name' => ['en' => 'Denmark', 'ar' => 'الدنمارك']],
            ['name' => ['en' => 'Djibouti', 'ar' => 'جيبوتي']],
            ['name' => ['en' => 'Dominica', 'ar' => 'دومينيكا']],
            ['name' => ['en' => 'Dominican Republic', 'ar' => 'جمهورية الدومينيكان']],
            ['name' => ['en' => 'Ecuador', 'ar' => 'الإكوادور']],
            ['name' => ['en' => 'Egypt', 'ar' => 'مصر']],
            ['name' => ['en' => 'El Salvador', 'ar' => 'السلفادور']],
            ['name' => ['en' => 'Equatorial Guinea', 'ar' => 'غينيا الاستوائية']],
            ['name' => ['en' => 'Eritrea', 'ar' => 'إريتريا']],
            ['name' => ['en' => 'Estonia', 'ar' => 'إستونيا']],
            ['name' => ['en' => 'Eswatini', 'ar' => 'إسواتيني']],
            ['name' => ['en' => 'Ethiopia', 'ar' => 'إثيوبيا']],
            ['name' => ['en' => 'Fiji', 'ar' => 'فيجي']],
            ['name' => ['en' => 'Finland', 'ar' => 'فنلندا']],
            ['name' => ['en' => 'France', 'ar' => 'فرنسا']],
            ['name' => ['en' => 'Gabon', 'ar' => 'الغابون']],
            ['name' => ['en' => 'Gambia', 'ar' => 'غامبيا']],
            ['name' => ['en' => 'Georgia', 'ar' => 'جورجيا']],
            ['name' => ['en' => 'Germany', 'ar' => 'ألمانيا']],
            ['name' => ['en' => 'Ghana', 'ar' => 'غانا']],
            ['name' => ['en' => 'Greece', 'ar' => 'اليونان']],
            ['name' => ['en' => 'Grenada', 'ar' => 'غرينادا']],
            ['name' => ['en' => 'Guatemala', 'ar' => 'غواتيمالا']],
            ['name' => ['en' => 'Guinea', 'ar' => 'غينيا']],
            ['name' => ['en' => 'Guinea-Bissau', 'ar' => 'غينيا بيساو']],
            ['name' => ['en' => 'Guyana', 'ar' => 'غيانا']],
            ['name' => ['en' => 'Haiti', 'ar' => 'هايتي']],
            ['name' => ['en' => 'Honduras', 'ar' => 'هندوراس']],
            ['name' => ['en' => 'Hungary', 'ar' => 'المجر']],
            ['name' => ['en' => 'Iceland', 'ar' => 'آيسلندا']],
            ['name' => ['en' => 'India', 'ar' => 'الهند']],
            ['name' => ['en' => 'Indonesia', 'ar' => 'إندونيسيا']],
            ['name' => ['en' => 'Iran', 'ar' => 'إيران']],
            ['name' => ['en' => 'Iraq', 'ar' => 'العراق']],
            ['name' => ['en' => 'Ireland', 'ar' => 'أيرلندا']],
            ['name' => ['en' => 'Italy', 'ar' => 'إيطاليا']],
            ['name' => ['en' => 'Jamaica', 'ar' => 'جامايكا']],
            ['name' => ['en' => 'Japan', 'ar' => 'اليابان']],
            ['name' => ['en' => 'Jordan', 'ar' => 'الأردن']],
            ['name' => ['en' => 'Kazakhstan', 'ar' => 'كازاخستان']],
            ['name' => ['en' => 'Kenya', 'ar' => 'كينيا']],
            ['name' => ['en' => 'Kiribati', 'ar' => 'كيريباتي']],
            ['name' => ['en' => 'Korea, North', 'ar' => 'كوريا الشمالية']],
            ['name' => ['en' => 'Korea, South', 'ar' => 'كوريا الجنوبية']],
            ['name' => ['en' => 'Kosovo', 'ar' => 'كوسوفو']],
            ['name' => ['en' => 'Kuwait', 'ar' => 'الكويت']],
            ['name' => ['en' => 'Kyrgyzstan', 'ar' => 'قيرغيزستان']],
            ['name' => ['en' => 'Laos', 'ar' => 'لاوس']],
            ['name' => ['en' => 'Latvia', 'ar' => 'لاتفيا']],
            ['name' => ['en' => 'Lebanon', 'ar' => 'لبنان']],
            ['name' => ['en' => 'Lesotho', 'ar' => 'ليسوتو']],
            ['name' => ['en' => 'Liberia', 'ar' => 'ليبيريا']],
            ['name' => ['en' => 'Libya', 'ar' => 'ليبيا']],
            ['name' => ['en' => 'Liechtenstein', 'ar' => 'ليختنشتاين']],
            ['name' => ['en' => 'Lithuania', 'ar' => 'ليتوانيا']],
            ['name' => ['en' => 'Luxembourg', 'ar' => 'لوكسمبورغ']],
            ['name' => ['en' => 'Madagascar', 'ar' => 'مدغشقر']],
            ['name' => ['en' => 'Malawi', 'ar' => 'مالاوي']],
            ['name' => ['en' => 'Malaysia', 'ar' => 'ماليزيا']],
            ['name' => ['en' => 'Maldives', 'ar' => 'جزر المالديف']],
            ['name' => ['en' => 'Mali', 'ar' => 'مالي']],
            ['name' => ['en' => 'Malta', 'ar' => 'مالطا']],
            ['name' => ['en' => 'Marshall Islands', 'ar' => 'جزر مارشال']],
            ['name' => ['en' => 'Mauritania', 'ar' => 'موريتانيا']],
            ['name' => ['en' => 'Mauritius', 'ar' => 'موريشيوس']],
            ['name' => ['en' => 'Mexico', 'ar' => 'المكسيك']],
            ['name' => ['en' => 'Micronesia', 'ar' => 'ميكرونيزيا']],
            ['name' => ['en' => 'Moldova', 'ar' => 'مولدوفا']],
            ['name' => ['en' => 'Monaco', 'ar' => 'موناكو']],
            ['name' => ['en' => 'Mongolia', 'ar' => 'منغوليا']],
            ['name' => ['en' => 'Montenegro', 'ar' => 'الجبل الأسود']],
            ['name' => ['en' => 'Morocco', 'ar' => 'المغرب']],
            ['name' => ['en' => 'Mozambique', 'ar' => 'موزمبيق']],
            ['name' => ['en' => 'Myanmar', 'ar' => 'ميانمار']],
            ['name' => ['en' => 'Namibia', 'ar' => 'ناميبيا']],
            ['name' => ['en' => 'Nauru', 'ar' => 'ناورو']],
            ['name' => ['en' => 'Nepal', 'ar' => 'نيبال']],
            ['name' => ['en' => 'Netherlands', 'ar' => 'هولندا']],
            ['name' => ['en' => 'New Zealand', 'ar' => 'نيوزيلندا']],
            ['name' => ['en' => 'Nicaragua', 'ar' => 'نيكاراغوا']],
            ['name' => ['en' => 'Niger', 'ar' => 'النيجر']],
            ['name' => ['en' => 'Nigeria', 'ar' => 'نيجيريا']],
            ['name' => ['en' => 'North Macedonia', 'ar' => 'مقدونيا الشمالية']],
            ['name' => ['en' => 'Norway', 'ar' => 'النرويج']],
            ['name' => ['en' => 'Oman', 'ar' => 'عُمان']],
            ['name' => ['en' => 'Pakistan', 'ar' => 'باكستان']],
            ['name' => ['en' => 'Palau', 'ar' => 'بالاو']],
            ['name' => ['en' => 'Palestine', 'ar' => 'فلسطين']],
            ['name' => ['en' => 'Panama', 'ar' => 'بنما']],
            ['name' => ['en' => 'Papua New Guinea', 'ar' => 'بابوا غينيا الجديدة']],
            ['name' => ['en' => 'Paraguay', 'ar' => 'باراغواي']],
            ['name' => ['en' => 'Peru', 'ar' => 'بيرو']],
            ['name' => ['en' => 'Philippines', 'ar' => 'الفلبين']],
            ['name' => ['en' => 'Poland', 'ar' => 'بولندا']],
            ['name' => ['en' => 'Portugal', 'ar' => 'البرتغال']],
            ['name' => ['en' => 'Qatar', 'ar' => 'قطر']],
            ['name' => ['en' => 'Romania', 'ar' => 'رومانيا']],
            ['name' => ['en' => 'Russia', 'ar' => 'روسيا']],
            ['name' => ['en' => 'Rwanda', 'ar' => 'رواندا']],
            ['name' => ['en' => 'Saint Kitts and Nevis', 'ar' => 'سانت كيتس ونيفيس']],
            ['name' => ['en' => 'Saint Lucia', 'ar' => 'سانت لوسيا']],
            ['name' => ['en' => 'Saint Vincent and the Grenadines', 'ar' => 'سانت فنسنت والغرينادين']],
            ['name' => ['en' => 'Samoa', 'ar' => 'ساموا']],
            ['name' => ['en' => 'San Marino', 'ar' => 'سان مارينو']],
            ['name' => ['en' => 'Sao Tome and Principe', 'ar' => 'ساو تومي وبرينسيبي']],
            ['name' => ['en' => 'Saudi Arabia', 'ar' => 'المملكة العربية السعودية']],
            ['name' => ['en' => 'Senegal', 'ar' => 'السنغال']],
            ['name' => ['en' => 'Serbia', 'ar' => 'صربيا']],
            ['name' => ['en' => 'Seychelles', 'ar' => 'سيشل']],
            ['name' => ['en' => 'Sierra Leone', 'ar' => 'سيراليون']],
            ['name' => ['en' => 'Singapore', 'ar' => 'سنغافورة']],
            ['name' => ['en' => 'Slovakia', 'ar' => 'سلوفاكيا']],
            ['name' => ['en' => 'Slovenia', 'ar' => 'سلوفينيا']],
            ['name' => ['en' => 'Solomon Islands', 'ar' => 'جزر سليمان']],
            ['name' => ['en' => 'Somalia', 'ar' => 'الصومال']],
            ['name' => ['en' => 'South Africa', 'ar' => 'جنوب أفريقيا']],
            ['name' => ['en' => 'South Sudan', 'ar' => 'جنوب السودان']],
            ['name' => ['en' => 'Spain', 'ar' => 'إسبانيا']],
            ['name' => ['en' => 'Sri Lanka', 'ar' => 'سريلانكا']],
            ['name' => ['en' => 'Sudan', 'ar' => 'السودان']],
            ['name' => ['en' => 'Suriname', 'ar' => 'سورينام']],
            ['name' => ['en' => 'Sweden', 'ar' => 'السويد']],
            ['name' => ['en' => 'Switzerland', 'ar' => 'سويسرا']],
            ['name' => ['en' => 'Syria', 'ar' => 'سوريا']],
            ['name' => ['en' => 'Taiwan', 'ar' => 'تايوان']],
            ['name' => ['en' => 'Tajikistan', 'ar' => 'طاجيكستان']],
            ['name' => ['en' => 'Tanzania', 'ar' => 'تنزانيا']],
            ['name' => ['en' => 'Thailand', 'ar' => 'تايلاند']],
            ['name' => ['en' => 'Timor-Leste', 'ar' => 'تيمور الشرقية']],
            ['name' => ['en' => 'Togo', 'ar' => 'توغو']],
            ['name' => ['en' => 'Tonga', 'ar' => 'تونغا']],
            ['name' => ['en' => 'Trinidad and Tobago', 'ar' => 'ترينيداد وتوباغو']],
            ['name' => ['en' => 'Tunisia', 'ar' => 'تونس']],
            ['name' => ['en' => 'Turkey', 'ar' => 'تركيا']],
            ['name' => ['en' => 'Turkmenistan', 'ar' => 'تركمانستان']],
            ['name' => ['en' => 'Tuvalu', 'ar' => 'توفالو']],
            ['name' => ['en' => 'Uganda', 'ar' => 'أوغندا']],
            ['name' => ['en' => 'Ukraine', 'ar' => 'أوكرانيا']],
            ['name' => ['en' => 'United Arab Emirates', 'ar' => 'الإمارات العربية المتحدة']],
            ['name' => ['en' => 'United Kingdom', 'ar' => 'المملكة المتحدة']],
            ['name' => ['en' => 'United States', 'ar' => 'الولايات المتحدة']],
            ['name' => ['en' => 'Uruguay', 'ar' => 'أوروغواي']],
            ['name' => ['en' => 'Uzbekistan', 'ar' => 'أوزبكستان']],
            ['name' => ['en' => 'Vanuatu', 'ar' => 'فانواتو']],
            ['name' => ['en' => 'Vatican City', 'ar' => 'الفاتيكان']],
            ['name' => ['en' => 'Venezuela', 'ar' => 'فنزويلا']],
            ['name' => ['en' => 'Vietnam', 'ar' => 'فيتنام']],
            ['name' => ['en' => 'Yemen', 'ar' => 'اليمن']],
            ['name' => ['en' => 'Zambia', 'ar' => 'زامبيا']],
            ['name' => ['en' => 'Zimbabwe', 'ar' => 'زيمبابوي']]
        ];

        foreach($countries as $country)
            Country::create($country);
    }
}
