<?php

namespace Database\Seeders;

use App\Models\Speciality;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SpecialitiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $specialities = [
            ['name' => ['en' => 'Medicine', 'ar' => 'الطب']],
            ['name' => ['en' => 'Dentistry', 'ar' => 'طب الأسنان']],
            ['name' => ['en' => 'Pharmacy', 'ar' => 'الصيدلة']],
            ['name' => ['en' => 'Nursing', 'ar' => 'التمريض']],
            ['name' => ['en' => 'Public Health', 'ar' => 'الصحة العامة']],
            ['name' => ['en' => 'Veterinary Medicine', 'ar' => 'الطب البيطري']],
            ['name' => ['en' => 'Engineering', 'ar' => 'الهندسة']],
            ['name' => ['en' => 'Computer Science', 'ar' => 'علوم الحاسب']],
            ['name' => ['en' => 'Information Technology', 'ar' => 'تكنولوجيا المعلومات']],
            ['name' => ['en' => 'Software Engineering', 'ar' => 'هندسة البرمجيات']],
            ['name' => ['en' => 'Civil Engineering', 'ar' => 'الهندسة المدنية']],
            ['name' => ['en' => 'Mechanical Engineering', 'ar' => 'الهندسة الميكانيكية']],
            ['name' => ['en' => 'Electrical Engineering', 'ar' => 'الهندسة الكهربائية']],
            ['name' => ['en' => 'Mechatronics', 'ar' => 'الميكاترونكس']],
            ['name' => ['en' => 'Architecture', 'ar' => 'العمارة']],
            ['name' => ['en' => 'Business Administration', 'ar' => 'إدارة الأعمال']],
            ['name' => ['en' => 'Accounting', 'ar' => 'المحاسبة']],
            ['name' => ['en' => 'Finance', 'ar' => 'التمويل']],
            ['name' => ['en' => 'Marketing', 'ar' => 'التسويق']],
            ['name' => ['en' => 'Management Information Systems', 'ar' => 'نظم المعلومات الإدارية']],
            ['name' => ['en' => 'Economics', 'ar' => 'الاقتصاد']],
            ['name' => ['en' => 'Political Science', 'ar' => 'العلوم السياسية']],
            ['name' => ['en' => 'Law', 'ar' => 'القانون']],
            ['name' => ['en' => 'Psychology', 'ar' => 'علم النفس']],
            ['name' => ['en' => 'Sociology', 'ar' => 'علم الاجتماع']],
            ['name' => ['en' => 'Social Work', 'ar' => 'العمل الاجتماعي']],
            ['name' => ['en' => 'Education', 'ar' => 'التربية']],
            ['name' => ['en' => 'Early Childhood Education', 'ar' => 'تربية الطفولة المبكرة']],
            ['name' => ['en' => 'Special Education', 'ar' => 'التربية الخاصة']],
            ['name' => ['en' => 'English Language and Literature', 'ar' => 'اللغة الإنجليزية وآدابها']],
            ['name' => ['en' => 'Arabic Language and Literature', 'ar' => 'اللغة العربية وآدابها']],
            ['name' => ['en' => 'French Language and Literature', 'ar' => 'اللغة الفرنسية وآدابها']],
            ['name' => ['en' => 'Linguistics', 'ar' => 'اللغويات']],
            ['name' => ['en' => 'Translation', 'ar' => 'الترجمة']],
            ['name' => ['en' => 'History', 'ar' => 'التاريخ']],
            ['name' => ['en' => 'Philosophy', 'ar' => 'الفلسفة']],
            ['name' => ['en' => 'Geography', 'ar' => 'الجغرافيا']],
            ['name' => ['en' => 'Mathematics', 'ar' => 'الرياضيات']],
            ['name' => ['en' => 'Statistics', 'ar' => 'الإحصاء']],
            ['name' => ['en' => 'Physics', 'ar' => 'الفيزياء']],
            ['name' => ['en' => 'Chemistry', 'ar' => 'الكيمياء']],
            ['name' => ['en' => 'Biology', 'ar' => 'علم الأحياء']],
            ['name' => ['en' => 'Biochemistry', 'ar' => 'الكيمياء الحيوية']],
            ['name' => ['en' => 'Environmental Science', 'ar' => 'العلوم البيئية']],
            ['name' => ['en' => 'Geology', 'ar' => 'الجيولوجيا']],
            ['name' => ['en' => 'Astronomy', 'ar' => 'علم الفلك']],
            ['name' => ['en' => 'Anthropology', 'ar' => 'الأنثروبولوجيا']],
            ['name' => ['en' => 'Archaeology', 'ar' => 'علم الآثار']],
            ['name' => ['en' => 'Fine Arts', 'ar' => 'الفنون الجميلة']],
            ['name' => ['en' => 'Graphic Design', 'ar' => 'التصميم الجرافيكي']],
            ['name' => ['en' => 'Interior Design', 'ar' => 'التصميم الداخلي']],
            ['name' => ['en' => 'Fashion Design', 'ar' => 'تصميم الأزياء']],
            ['name' => ['en' => 'Music', 'ar' => 'الموسيقى']],
            ['name' => ['en' => 'Theatre', 'ar' => 'المسرح']],
            ['name' => ['en' => 'Film and Television', 'ar' => 'السينما والتلفزيون']],
            ['name' => ['en' => 'Journalism', 'ar' => 'الصحافة']],
            ['name' => ['en' => 'Media Studies', 'ar' => 'دراسات الإعلام']],
            ['name' => ['en' => 'Communications', 'ar' => 'الاتصالات']],
            ['name' => ['en' => 'Hospitality Management', 'ar' => 'إدارة الضيافة']],
            ['name' => ['en' => 'Tourism Management', 'ar' => 'إدارة السياحة']],
            ['name' => ['en' => 'Culinary Arts', 'ar' => 'فنون الطهي']],
            ['name' => ['en' => 'Sports Science', 'ar' => 'علوم الرياضة']],
            ['name' => ['en' => 'Physical Education', 'ar' => 'التربية الرياضية']],
            ['name' => ['en' => 'Library and Information Science', 'ar' => 'علم المكتبات والمعلومات']],
            ['name' => ['en' => 'Artificial Intelligence', 'ar' => 'الذكاء الاصطناعي']],
            ['name' => ['en' => 'Cybersecurity', 'ar' => 'الأمن السيبراني']],
            ['name' => ['en' => 'Data Science', 'ar' => 'علم البيانات']],
            ['name' => ['en' => 'Robotics', 'ar' => 'الروبوتات']],
            ['name' => ['en' => 'Biomedical Engineering', 'ar' => 'الهندسة الطبية الحيوية']],
            ['name' => ['en' => 'Industrial Engineering', 'ar' => 'الهندسة الصناعية']],
            ['name' => ['en' => 'Petroleum Engineering', 'ar' => 'هندسة البترول']],
            ['name' => ['en' => 'Chemical Engineering', 'ar' => 'الهندسة الكيميائية']],
            ['name' => ['en' => 'Agricultural Engineering', 'ar' => 'الهندسة الزراعية']],
            ['name' => ['en' => 'Agriculture', 'ar' => 'الزراعة']],
            ['name' => ['en' => 'Forestry', 'ar' => 'الغابات']],
            ['name' => ['en' => 'Horticulture', 'ar' => 'البستنة']],
            ['name' => ['en' => 'Animal Science', 'ar' => 'علم الحيوان']],
            ['name' => ['en' => 'Food Science', 'ar' => 'علم الغذاء']],
            ['name' => ['en' => 'Marine Biology', 'ar' => 'علم الأحياء البحرية']],
            ['name' => ['en' => 'Oceanography', 'ar' => 'علم المحيطات']],
            ['name' => ['en' => 'Forensic Science', 'ar' => 'العلوم الجنائية']],
            ['name' => ['en' => 'Criminology', 'ar' => 'علم الجريمة']],
            ['name' => ['en' => 'Religious Studies', 'ar' => 'الدراسات الدينية']],
            ['name' => ['en' => 'Islamic Studies', 'ar' => 'الدراسات الإسلامية']],
            ['name' => ['en' => 'Christian Theology', 'ar' => 'اللاهوت المسيحي']],
            ['name' => ['en' => 'Jewish Studies', 'ar' => 'الدراسات اليهودية']],
            ['name' => ['en' => 'Gender Studies', 'ar' => 'دراسات النوع الاجتماعي']],
            ['name' => ['en' => 'Development Studies', 'ar' => 'دراسات التنمية']],
            ['name' => ['en' => 'Peace and Conflict Studies', 'ar' => 'دراسات السلام والنزاعات']],
            ['name' => ['en' => 'International Relations', 'ar' => 'العلاقات الدولية']],
            ['name' => ['en' => 'Logistics and Supply Chain Management', 'ar' => 'اللوجستيات وإدارة سلسلة التوريد']],
            ['name' => ['en' => 'Entrepreneurship', 'ar' => 'ريادة الأعمال']],
            ['name' => ['en' => 'Actuarial Science', 'ar' => 'الاكتواريا']],
            ['name' => ['en' => 'Game Design', 'ar' => 'تصميم الألعاب']],
            ['name' => ['en' => 'Animation', 'ar' => 'الرسوم المتحركة']],
        ];

        foreach($specialities as $speciality)
            Speciality::create($speciality);
    }
}
